sandpit/urls.py
from django.conf.urls import patterns, include, url

from blog import views as blogview
from helpdesk import views as helpdeskview

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns



from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sandpit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r'^admin/', include(admin.site.urls)),
	
	#url(r'^$', helpdeskview.helpdesk),
	url(r'^$', blogview.signin),

	### BLOG ###
	url(r'^blog/$', blogview.blog),
	url(r'^notes/$', blogview.blog),
	
	url(r'^add-note/$', blogview.edit_note),
	url(r'^note/(?P<note_id>\d+)/$', blogview.note),
	url(r'^note/(?P<note_id>\d+)/edit/$', blogview.edit_note),
	url(r'^note/(?P<note_id>\d+)/delete/$', blogview.delete_note),

	url(r'^comment/(?P<comment_id>\d+)/delete/$', blogview.delete_comment),

	url(r'^users/$', blogview.users),
	url(r'^user/(?P<user_id>\d+)/$', blogview.user),
	url(r'^user/(?P<user_id>\d+)/notes/$', blogview.blog),

	url(r'^signup/$', blogview.signup),
	url(r'^user/(?P<user_id>\d+)/edit/$', blogview.edit_user),	
	url(r'^user/(?P<user_id>\d+)/delete/$', blogview.delete_user),	
	url(r'^signin/$', blogview.signin),
	url(r'^logout/$', blogview.logout),

	url(r'^passwd/$', blogview.passwd),

	### HELPDESK ###
	url(r'^helpdesk/$', helpdeskview.helpdesk),

	url(r'^create-ticket/$', helpdeskview.create_ticket),
	url(r'^create-group/$', helpdeskview.edit_group),
	url(r'^groups/$', helpdeskview.groups),
	url(r'^group/(?P<group_id>\d+)/delete/$', helpdeskview.delete_group),
	url(r'^group/(?P<group_id>\d+)/edit/$', helpdeskview.edit_group),
	url(r'^ticket/(?P<ticket_id>\d+)/$', helpdeskview.ticket),

	url(r'^ticket/(?P<ticket_id>\d+)/edit/$', helpdeskview.edit_ticket),
	url(r'^ticket/(?P<ticket_id>\d+)/delete/$', helpdeskview.delete_ticket),

	### THIS STUFF IS FOR SOCIAL AUTH ##################################
	url('', include('social.apps.django_app.urls', namespace='social')),
	url('', include('django.contrib.auth.urls', namespace='auth')),
	###################################################################
)






urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms.models import modelform_factory

import datetime
import os

class Note(models.Model):
	title 				= models.CharField(max_length=100)
	author 				= models.ForeignKey(User)
	publication_date 	= models.DateTimeField(blank=False, null=False)
	text 				= models.TextField(max_length=10000)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.id:
			self.publication_date = datetime.datetime.now()
		return super(Note, self).save(*args,**kwargs)



def extension(self):
	name, extension = os.path.splitext(self)
	return extension

def get_upload_file_name(instance, filename):
	return "blog/media/images/%s_%s%s" % ("profile".replace('.','_'), instance.user.username, extension(filename))
	#return "blog/media/images/%s%s" % (instance.user.username, extension(filename))

def get_deleted_user():
    return User.objects.get_or_create(username='deleted')[0]

class UserProfile(models.Model):
	user 	= models.OneToOneField(User, unique=True)#, on_delete=models.SET(get_deleted_user))
	picture = models.ImageField(upload_to=get_upload_file_name, blank=True, null=True)

	def __unicode__(self):
		return unicode(self.picture.name) 

	def save(self, *args, **kwargs):
		try:
			existing = UserProfile.objects.get(user=self.user)
			self.id = existing.id #force update instead of insert
		except UserProfile.DoesNotExist:
			pass 
		models.Model.save(self, *args, **kwargs)


class Comment(models.Model):
	note 				= models.ForeignKey(Note)
	text 				= models.TextField(max_length=10000)
	author 				= models.ForeignKey(User)
	publication_date 	= models.DateTimeField(blank=False, null=False)
	#parent				= models.ForeignKey('self', blank=True, null=True, related_name='child_set')

	def __str__(self):
		return self.text

	def save(self, *args, **kwargs):
		if not self.id:
			self.publication_date = datetime.datetime.now()
		return super(Comment, self).save(*args,**kwargs)

blog/forms.py
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User

from blog.models import Note
from blog.models import Comment
from blog.models import UserProfile


from pagedown.widgets import PagedownWidget 



from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Hidden, Fieldset
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions


class NoteForm(forms.ModelForm):
	class Meta:
		model = Note
		
		fields = ['title', 'text']

	def clean_message(self):
		text = self.cleaned_data['text']
		num_words = len(text.split())
		if num_words < 4:
			raise forms.ValidationError("Text is too small!")
		return text

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['text']

	def clean_message(self):
		text = self.cleaned_data['text']
		num_words = len(text.split())
		if num_words < 4:
			raise forms.ValidationError("Text is too small!")
		return text


class SignupForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

	def clean_message(self):
		password = self.cleaned_data['password']
		if len(password) < 5:
			raise forms.ValidationError("Password is way too simple. Make up a new one, please.")
		return password

	def clean_email(self):
		email = self.cleaned_data.get('email')
		username = self.cleaned_data.get('username')
		if email and User.objects.filter(email=email).exclude(username=username).count():
			raise forms.ValidationError(u'This email has already been registered.')
		return email

class EditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email']

class ProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ['picture']

class EditFormForSuperuser(forms.ModelForm):
	#newpassword = forms.CharField(required=False, label='New password')
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password', 'is_active', 'is_staff', 'is_superuser', 'groups']

		widgets = {
            'groups': forms.SelectMultiple(attrs={'class': 'chosen groups'}),
        }

class SigninForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'password']

	def __init__(self, *args, **kwargs):
		super(SigninForm, self).__init__(*args, **kwargs)

		for fieldname in ['username', 'password']:
			self.fields[fieldname].help_text = None

class PasswdForm(forms.Form):
	oldpassword = forms.CharField(required=True, label='Current password')
	repeat = forms.CharField(required=True, label='Repeat current password')
	newpassword = forms.CharField(required=True, label='New password')


#	def is_valid(self):
#		valid = super(SigninForm, self).is_valid()
#		if not valid:
#			return valid
#		try:
#			user = User.objects.get(
#				Q(username=self.cleaned_data['username']) | Q(email=self.cleaned_data['username'])
#			)
#		except User.DoesNotExist:
#			self._errors['no_user'] = 'User does not exist'
#			return False
#		if not check_password(self.cleaned_data['password'], user.password):
#			self._errors['invalid_password'] = 'Password is invalid'
#			return False
#		return True

blog/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.http import Http404
from django.http import HttpResponse

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404

from django.contrib import auth

from django.template import Template, Context
from django.template.loader import get_template

from blog.models import *
from blog.forms import *

from django.contrib.auth.models import User

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth.hashers import check_password, make_password

import time

def blog(request, user_id=None):
	if user_id:
		notes_list=list(Note.objects.filter(author__id=user_id))
		if not notes_list:
			return HttpResponse("Selected user doesn't have any notes")
	else:
		notes_list=Note.objects.all().order_by('-id')

	paginator = Paginator(notes_list, 3, orphans=0, allow_empty_first_page=True) # Show 3 notes per page
	
	page = request.GET.get('page')
	try:
		notes = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		notes = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		notes = paginator.page(paginator.num_pages)

		#import os
		#print(os.path.join(os.path.dirname(__file__), 'media').replace('\\','/'))

	return render(request, 'blog.html', {'notes': notes})


def edit_note(request, note_id=None, template_name='edit_note.html'):
	if note_id:
		note = get_object_or_404(Note, pk=note_id)
		if note.author != request.user:
			if not request.user.is_superuser:
				return HttpResponse("404")
	else:
		note = Note(author=request.user)

	if request.user.is_authenticated():
		if request.method == 'POST':
			form = NoteForm(request.POST, instance=note)
			if form.is_valid():
				note = form.save(commit=False)
				note.author = request.user
				note.save()
				if note_id:
					return HttpResponseRedirect('/note/%s/' % note_id)
				else:
					return HttpResponseRedirect('/')
		else:
			form = NoteForm(instance=note)
		return render_to_response(template_name, {'form': form}, context_instance=RequestContext(request))
	else:
		return HttpResponse('For authenticated users only!')


def note(request, note_id=None):
	note = Note.objects.get(id=note_id)
	author = note.author

	### Comment section ###
	if request.user.is_authenticated():
		if request.method == 'POST':
			commentForm = CommentForm(request.POST)
			if commentForm.is_valid():
				comment = commentForm.save(commit=False)
				comment.note = note
				comment.author = request.user
				comment.text = request.POST['text']
				print("COMMENT ADDED! ", comment.text)
				comment.save()
				return HttpResponseRedirect('/note/%s/' % note_id)
		else:
			commentForm = CommentForm()
	else:
		commentForm = CommentForm()
	#else:
	#	return HttpResponse('For authenticated users only!')

	comments_list=Comment.objects.filter(note__id=note_id)
	#######################

	return render(request, 'note.html', {'note':note, 'author':author, 'commentForm':commentForm, 'comments_list':comments_list})	


def delete_note(request, note_id):
	note=Note.objects.get(id=note_id)
	author = note.author
	if request.user.is_superuser or author == request.user:
		note.delete()
		return HttpResponseRedirect('/')
	else:
		return HttpResponse("You are not allowed to do that!")

def delete_comment(request, comment_id):
	comment=Comment.objects.get(id=comment_id)
	note=comment.note
	author = comment.author
	if request.user.is_superuser or author == request.user:
		comment.delete()
		return HttpResponseRedirect('/note/%s/' % note.id)
	else:
		return HttpResponse("You are not allowed to do that!")


def users(request):
	if request.user.is_superuser:
		users=User.objects.all()
		return render(request, 'users.html', {'users': users})
	else:
		return HttpResponse("For superusers only")


def user(request, user_id):
	author=User.objects.get(id=user_id)
	return render(request, 'user.html', {'author': author})


def delete_user(request, user_id):
	user=User.objects.get(id=user_id)
	if request.user.is_superuser or user.id == request.user.id:
		if user.id != request.user.id:
			user.delete()
			return HttpResponseRedirect('/users/')
		else:
			user.delete()
			return HttpResponseRedirect('/')
	else:
		return HttpResponse("You are not allowed to do that!")


def signup(request):
	user = User(id=request.user.id)

	if request.method == 'POST':
		userForm = SignupForm(request.POST, instance=user)

		if userForm.is_valid():
			user = userForm.save(commit=False)
			user.set_password(userForm.cleaned_data['password'])
			#user = User.objects.create_user(
			#	username = request.POST['username'], 
			#	email = request.POST['email'],
			#	password = request.POST['password']
			#)
			user.save()

			return HttpResponseRedirect('/signin/')

	else:
		userForm = SignupForm(instance=user)
	return render(request, 'signup.html', {'userForm': userForm})


def edit_user(request, user_id=None):
	user = get_object_or_404(User, pk=user_id)
	print(user_id != request.user.id)
	print(user_id)
	print(request.user.id)
	if int(user_id) != request.user.id and not request.user.is_superuser:
		return HttpResponse("You are not allowed to do that!")	
	
	if request.method == 'POST':
		if request.user.is_superuser:
			userForm = EditFormForSuperuser(request.POST, instance=user)
		else:
			userForm = EditForm(request.POST, instance=user)

		if userForm.is_valid():
			userForm.save()

			#if request.user.is_superuser:
			#	newpassword = userForm.cleaned_data['newpassword']
			#	passwd = make_password(newpassword)
			#	user.password = passwd
			#	user.save()

			profileForm = ProfileForm(request.POST, request.FILES, instance=user)
			if profileForm.is_valid():
				profile = profileForm.save(commit=False)

				# Superuser can change anyones' picture
				# And users can change only their own pictures
				if request.user.is_superuser:
					profile.user = user
				else:
					profile.user = request.user
				profile.save()
			return HttpResponseRedirect('/user/%s/' % user.id)
	else:
		# Different forms for superusers, users and guests
		if request.user.is_superuser:
			userForm = EditFormForSuperuser(instance=user)
		else:
			userForm = EditForm(instance=user)		
		profileForm = ProfileForm(instance=user)
	return render(request, 'edit_user.html', {'userForm': userForm, 'profileForm': profileForm})


def signin(request):
	if request.user is not None and request.user.is_active:
		return HttpResponseRedirect('helpdesk')
	else:
		if request.method == 'POST':
			form = SigninForm(request.POST)
			#if form.is_valid():
			#username = request.POST.get('username', '')
			#password = request.POST.get('password', '')
			username = request.POST['username']
			password = request.POST['password']
			user = auth.authenticate(username=username, password=password)
			if user is not None and user.is_active:
				auth.login(request, user)
				return HttpResponseRedirect('/helpdesk/')
			else:
				return HttpResponse("ERROR")
		else:
			form = SigninForm()
	return render(request, 'signin.html', {'form': form})


def logout(request):
	auth.logout(request)
	response = HttpResponseRedirect('/')
	response.delete_cookie('sessionid')
	return response


def passwd(request):
	if request.user.is_authenticated and request.user.is_active:
		if request.method == "POST":
			passwdForm = PasswdForm(request.POST)

			if passwdForm.is_valid():
				oldpassword = passwdForm.cleaned_data['oldpassword']
				repeat = passwdForm.cleaned_data['repeat']
				encoded = request.user.password

				if oldpassword == repeat and check_password(oldpassword, encoded):
					newpassword = passwdForm.cleaned_data['newpassword']
					passwd = make_password(newpassword)
					request.user.password = passwd
					request.user.save()

					return HttpResponseRedirect("/user/%s/" % request.user.id)					
				else:
					return HttpResponse("Check your current password!")
		else:
			passwdForm = PasswdForm()

	return render(request, 'passwd.html', {'passwdForm': passwdForm})

sandpit/templates/blog/blog.html
{% extends "base.html" %}

{% block title %}Blog{% endblock %}

{% block content %}

	<h1>Notes</h1>

	<!-- {% load staticfiles %}
	<img src="{% static 'media/default.jpg' %}" />
	-->

	<!-- <img src="{{ MEDIA_URL }}blog/media/images/default.jpg" width="500" />
	<br /><br /><br />
	-->

	
	{% if user.is_authenticated %}
		<a href="/add-note/" id="button">Add note</a>
	{% endif %}
	
	{% for note in notes %}
		<div class="post">
			<h2><a href="/note/{{ note.id }}">{{ note }}</a></h2>
			<small>Author: <a href="/user/{{ note.author.id }}/">{{ note.author }}</a>, Date: {{ note.publication_date|date:"d M. Y H:i" }}</small>
			<p>{{ note.text | truncatewords:150 }}<!--<br /><a href="/note/{{ note.id }}">[Read more]</a>--></p>
			<small>{{ note.comment_set.count }} comments</small><br />
		</div>

		<!--<table class="post">
			<tr id="postheader"> 
				<td id="tdhead"><h2><a href="/note/{{ note.id }}">{{ note }}</a></h2></td>
			</tr>
			<tr> 
				<td><p>{{ note.text | truncatewords:150 }}<br /><a href="/note/{{ note.id }}">[Read more]</a></p></td>
			</tr>
			<tr>
				<td><small>Author: <a href="/user/{{ note.author.id }}/">{{ note.author }}</a>, Date: {{ note.publication_date }}</small></td>
			</tr>
		</table>-->
		
	{% endfor %}


	<div class="pagination">
		<span class="step-links">
			{% if notes.has_previous %}
				<a href="?page={{ notes.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ notes.number }} of {{ notes.paginator.num_pages }}
			</span>


			{% if notes.has_next %}
				<a href="?page={{ notes.next_page_number }}">next</a>
			{% endif %}
		</span>
	</div>

{% endblock %}

sandpit/templates/blog/blogbase.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "base.css" %}" />

    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    {{ form.media }}

    <!-- TAGS (TAG-IT) 
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "tagit/js/tag-it.js" %}" type="text/javascript" charset="utf-8"></script>

    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link href="{% static "tagit/css/jquery.tagit.css" %}" rel="stylesheet" type="text/css">
     TAGS (TAG-IT) -->



    <title>{% block title %}{% endblock %}</title>
</head>
<body>


    {% block header %}
        <nav>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <a href="/users/">Users</a>
                {% endif %}
                <a href="/blog/">Notes</a>

                <a href="/user/{{ user.id }}">
                    {% if user.userprofile.picture %}
                        <img src="{{ user.userprofile.picture.url }}" width="20" height="20" />
                    {% else %}
                        <img src="{{ MEDIA_URL }}blog/media/images/default.jpg" width="20" height="20" />
                    {% endif %}
                    
                    {{ user }}
                </a>
                
                <a href="/logout/">Log out</a> 
            {% else %}
                <a href="/signup/">Sign up</a>
                <a href="/signin/">Sign in</a>
            {% endif %}

        </nav>
    {% endblock %}

    <div class="content">{% block content %}{% endblock %}</div>
    




    {% block footer %}{% endblock %}
</body>
</html>

sandpit/templates/blog/edit_note.html
{% extends "base.html" %}

{% block title %}Add note{% endblock %}

{% block content %}

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>

        <!-- <script type="text/javascript">
            $(document).ready(function() {
                $("#myTags").tagit();
            });
        </script>
        <ul id="myTags">
            <li>Tag1</li>
            <li>Tag2</li>
        </ul> -->


        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
    <br />
    <a href="/" id="button">Go back</a>

{% endblock %}

sandpit/templates/blog/edit_user.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
    
    {% if not user.is_authenticated %}

        <h1>You are not allowed to do that</h1>

    {% else %}

        <h1>Profile</h1>

        {% if userForm.errors %}
            <p style="color: red;">
                Please correct the error{{ userForm.errors | pluralize }} below.
            </p>
        {% endif %}

        <form action="" method="POST" enctype="multipart/form-data">
            <table>
                {{ userForm.as_table }}
                {{ profileForm.as_table }}
            </table>
            {% csrf_token %}
            <input type="submit" name="submit" value="Submit">
        </form>

        <p><a href="/passwd/" id="button">Change password</a></p>

        <script type="text/javascript">$(".chosen").chosen();</script>


        <!--<form action="" method="post">
            <table>
                {{ profileForm.as_table }}
            </table>
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>-->

    {% endif %}

{% endblock %}

sandpit/templates/blog/note.html
{% extends "base.html" %}

{% block title %}Note{% endblock %}
	
	{% load staticfiles %}
	<!--<link rel="stylesheet" type="text/css" href="{% static "editor-master/editor.css" %}" />
	<script type="text/javascript" src="{% static "editor-master/src/editor.js" %}"></script>
	-->
	<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

{% block content %}

    <h1>{{ note }}</h1>
	Author: <a href="/user/{{ note.author.id }}/">{{ note.author }}</a><br />
	Publication date: {{ note.publication_date|date:"d M. Y H:i" }}
	
	<div>
		{{ note.text | striptags | urlize | linebreaks }}
	</div>

	{% if user.is_superuser or note.author == user %}
		<a href="/note/{{ note.id }}/edit/" id="button">Edit note</a>
		<a href="/note/{{ note.id }}/delete/" id="button">Delete note</a>
	{% endif %}

	<hr />
	{% for comment in comments_list %}	
		{% if note.author == comment.author %}
			<div class="comment" id="authorcomment">
		{% else %}
			<div class="comment">
		{% endif %}
				<small>
					Author:

					{% if comment.author.userprofile.picture %}
                        <img src="{{ comment.author.userprofile.picture.url }}" width="20" height="20" />
                    {% else %}
                        <img src="{{ MEDIA_URL }}blog/media/images/default.jpg" width="20" height="20" />
                    {% endif %} 
                    
					<a href="/user/{{ comment.author.id }}/">{{ comment.author }}</a>, Date: {{ comment.publication_date|date:"d M. Y H:i" }}
				</small>
				<p>{{ comment.text }}</p>
				{% if user.is_superuser or note.author == user %}
					<a href="/comment/{{ comment.id }}/delete/" id="button">Delete this comment</a>
					<div class="reply" id="button" onClick="document.getElementById('id_text').value+='{{ comment.author }}, '">Reply</div>
				{% endif %}

				<!-- FOR REPLYING
				<script type="text/javascript">
					function reply(){
						document.getElementById('id_text').value+='{{ comment.author }}, '
						document.getElementById('id_text').focus()
						
						elem=document.getElementById('id_text')
				        var elemLen = elem.value.length;
				        // For IE Only
				        if (document.selection) {
				            // Set focus
				            elem.focus();
				            // Use IE Ranges
				            var oSel = document.selection.createRange();
				            // Reset position to 0 & then set at end
				            oSel.moveStart('character', -elemLen);
				            oSel.moveStart('character', elemLen);
				            oSel.moveEnd('character', 0);
				            oSel.select();
				        }
				        else if (elem.selectionStart || elem.selectionStart == '0') {
				            // Firefox/Chrome
				            elem.selectionStart = elemLen;
				            elem.selectionEnd = elemLen;
				            elem.focus();
				        } // if
				    } // SetCaretAtEnd()
				</script>
				 ############ -->

			</div>
	{% endfor %}

	{% if user.is_authenticated %}
		<form action="" method="post">
			<table>
				{{ commentForm.as_table }}
			</table>
			{% csrf_token %}
			<input type="submit" value="Submit">
		</form>
	{% endif %}

{% endblock %}

sandpit/templates/blog/passwd.html
{% extends "base.html" %}

{% block title %}Changing password{% endblock %}

{% block content %}
    
    {% if not user.is_authenticated %}

        <h1>You are not allowed to do that</h1>

    {% else %}

        {% if userForm.errors %}
            <p style="color: red;">
                Please correct the error{{ userForm.errors | pluralize }} below.
            </p>
        {% endif %}

        <form action="" method="POST" enctype="multipart/form-data">
            <table>
                {{ passwdForm.as_table }}
            </table>
            {% csrf_token %}
            <input type="submit" name="submit" value="Submit">
        </form>

    {% endif %}

{% endblock %}

sandpit/templates/blog/signin.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    {% load staticfiles %}
    
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "base.css" %}" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>

{% block content %}

    {% if user.is_authenticated %}

        <h1>You are already signed in</h1>

    {% else %}
        
        <div class="wrapper_sign">
            <div class="formdiv">
                <!--<h1>Sign In</h1>-->

                       
                {% if form.errors %}
                    <p style="color: red;">
                        Please correct the error{{ form.errors | pluralize }} below.
                    </p>
                {% endif %}

                <form action="" method="post" class="signform">
                    <table id="sign">
                        {{ form.as_table }}
                    </table>
                    {% csrf_token %}
                    <input type="submit" value="Sign in">
                </form>
            </div>
        </div>


        <!-- ### THIS STUFF IS FOR SOCIAL AUTH ### 
        <ul>
            <li>
                <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
            </li>
            <li>
                <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
            </li>
            <li>
                <a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a>
            </li>
        </ul>
         ################################### -->


    {% endif %}

    <!--<a href="/" id="button">Go back</a>-->

{% endblock %}
</html>